### ISSUE TITLE
No Submit button

### ISSUE THREAD

**Issue by lyd70** [nuvoleweb/atrium_folders#21]
When jQuery Update is enabled the folders file Submit button does not show up.
When jQuery Update is disabled the Submit button does show up but other functions incl. Customize Dashboard do not work.
How can this be fixed? 
It hurts!

**Comment by lyd70** [comment]
If anyone can show me how to solve this problem it is most appreciated.

**Comment by nuvoleweb** [comment]
Are you using the latest version? At least jQuey Update compatibility should be OK in the latest (11/11/2011) version. If still current, please reopen this issue.

**Comment by diazjuan** [comment]
Hi, I am using the latest version of Open Atrium and it seems that I have the same problem. When trying to attach a file to atrium folders in "Attach files to this folder", i got the browse button, and the delete button, but never the "Save button", so even if I select a file the folder always says "no file has been uploaded yet". The drag and drop feature is not working so I cannot drag the file either. 

I confirmed that the line described in https://github.com/nuvoleweb/atrium_folders/issues/15 is in my code, and disabling jQuery sounds weird for me, because probably I will need it later. 

Thanks a lot.

Thanks a lot,
